## Import The Libraries

In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,root_mean_squared_error

## Load Dataset

In [117]:
dataset=pd.read_csv("AmesHousing.csv")

## Data Validation

In [118]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Order            2930 non-null   int64  
 1   PID              2930 non-null   int64  
 2   MS SubClass      2930 non-null   int64  
 3   MS Zoning        2930 non-null   str    
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64  
 6   Street           2930 non-null   str    
 7   Alley            198 non-null    str    
 8   Lot Shape        2930 non-null   str    
 9   Land Contour     2930 non-null   str    
 10  Utilities        2930 non-null   str    
 11  Lot Config       2930 non-null   str    
 12  Land Slope       2930 non-null   str    
 13  Neighborhood     2930 non-null   str    
 14  Condition 1      2930 non-null   str    
 15  Condition 2      2930 non-null   str    
 16  Bldg Type        2930 non-null   str    
 17  House Style      2930 non

In [119]:
dataset.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,2929.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2928.000000,2928.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2771.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,559.262547,1051.614544,1159.557679,335.455973,4.676792,1499.690444,0.431352,0.061134,1.566553,0.379522,2.854266,1.044369,6.443003,0.599317,1978.132443,1.766815,472.819734,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,169.168476,439.494153,440.615067,391.890885,428.395715,46.310510,505.508887,0.524820,0.245254,0.552941,0.502629,0.827731,0.214076,1.572964,0.647921,25.528411,0.760566,215.046549,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,219.000000,793.000000,876.250000,0.000000,0.000000,1126.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1960.000000,1.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,466.000000,990.000000,1084.000000,0.000000,0.000000,1442.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,480.000000,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,0.000000,802.000000,1302.000000,1384.000000,703.750000,0.000000,1742.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,3.000000,2.000000,4.000000,2.000000,8.000000,3.000000,15.000000,4.000000,2207.000000,5.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000


In [120]:
pd.set_option('display.max_rows',None)
dataset.isnull().sum().sort_values(ascending=False)

Pool QC            2917
Misc Feature       2824
Alley              2732
Fence              2358
Mas Vnr Type       1775
Fireplace Qu       1422
Lot Frontage        490
Garage Qual         159
Garage Yr Blt       159
Garage Cond         159
Garage Finish       159
Garage Type         157
Bsmt Exposure        83
BsmtFin Type 2       81
Bsmt Qual            80
Bsmt Cond            80
BsmtFin Type 1       80
Mas Vnr Area         23
Bsmt Full Bath        2
Bsmt Half Bath        2
Total Bsmt SF         1
BsmtFin SF 1          1
BsmtFin SF 2          1
Garage Area           1
Garage Cars           1
Bsmt Unf SF           1
Electrical            1
Lot Shape             0
Street                0
Lot Area              0
MS SubClass           0
MS Zoning             0
Order                 0
PID                   0
House Style           0
Bldg Type             0
Condition 2           0
Condition 1           0
Neighborhood          0
Land Slope            0
Lot Config            0
Utilities       

In [121]:
dataset.duplicated().sum()

np.int64(0)

## Handling Missing Values

In [122]:
# Categorical Features
dataset["Pool QC"] = dataset["Pool QC"].fillna("No Pool")
dataset["Misc Feature"] = dataset["Misc Feature"].fillna("None")
dataset["Alley"] = dataset["Alley"].fillna("No Alley")
dataset["Fence"] = dataset["Fence"].fillna("No Fence")
dataset["Mas Vnr Type"] = dataset["Mas Vnr Type"].fillna("None")
dataset["Fireplace Qu"] = dataset["Fireplace Qu"].fillna("No Fireplace")
dataset["Garage Qual"] = dataset["Garage Qual"].fillna("No Garage")
dataset["Garage Cond"] = dataset["Garage Cond"].fillna("No Garage")
dataset["Garage Finish"] = dataset["Garage Finish"].fillna("No Garage")
dataset["Garage Type"] = dataset["Garage Type"].fillna("No Garage")
dataset["Bsmt Exposure"] = dataset["Bsmt Exposure"].fillna("No Basement")
dataset["BsmtFin Type 1"] = dataset["BsmtFin Type 1"].fillna("No Basement")
dataset["BsmtFin Type 2"] = dataset["BsmtFin Type 2"].fillna("No Basement")
dataset["Bsmt Qual"] = dataset["Bsmt Qual"].fillna("No Basement")
dataset["Bsmt Cond"] = dataset["Bsmt Cond"].fillna("No Basement")
# Numerical Features
zero_fill_columns = [
    "Mas Vnr Area",
    "Bsmt Full Bath",
    "Bsmt Half Bath",
    "Total Bsmt SF",
    "BsmtFin SF 1",
    "BsmtFin SF 2",
    "Bsmt Unf SF",
    "Garage Area",
    "Garage Cars"
]
dataset[zero_fill_columns] = dataset[zero_fill_columns].fillna(0)
dataset["Electrical"] = dataset["Electrical"].fillna(dataset["Electrical"].mode()[0])


dataset.loc[dataset["Garage Type"] == "No Garage", "Garage Yr Blt"] = 0


dataset["Garage Yr Blt"] = dataset["Garage Yr Blt"].fillna(dataset["Year Built"])


dataset["Lot Frontage"] = dataset["Lot Frontage"].fillna(dataset["Lot Frontage"].median())



In [123]:
dataset.isnull().sum().sum() 
# Now We Did handle the all missing values

np.int64(0)

### Feature Selection

In [124]:
X = dataset.drop("SalePrice", axis=1)
y = dataset["SalePrice"]

## Encoding 

In [125]:
categorical_columns = X.select_dtypes(include=["object", "string"]).columns
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(sparse_output=False),categorical_columns)],remainder='passthrough')
X = ct.fit_transform(X)
X = np.array(X)
print(X)

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 5.000e+00 2.010e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 6.000e+00 2.010e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.250e+04 6.000e+00 2.010e+03]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 7.000e+02 7.000e+00 2.006e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 4.000e+00 2.006e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 1.100e+01 2.006e+03]]


## Spliting The Teain set and Test set

In [126]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

## Training the Model 

In [127]:
regressor=LinearRegression()
regressor.fit(X_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](320,)","[ -0. , -0. , 0. ,...,-12.57, 0.01, -0. ]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-8329
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,320
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int,9
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](320,)","[9.14e+09,3.79e+05,4.02e+04,...,1.01e-06,3.74e-07,5.71e-09]"


## Predicting the Test set Result

In [129]:
y_pred=regressor.predict(X_test)
print(y_pred)


[ 95819.16416256 216833.01214742 186293.88766128 203792.26418354
 204909.76541507 122120.1643931  212551.3304067  162852.5839767
 140480.65216734 145749.34298109 184374.86792774 195159.45636182
 163394.03863246  93345.18972702 224191.38480366 282667.61838012
 115342.34403702 220758.24262382 126366.71371661 163432.96474151
 122156.49012875 166676.22648578 178622.89117508 169675.72304461
  50092.87944138 130805.51965325 155288.92156678 262758.85326937
 196431.92714033 247954.90934913 169834.96467306 172614.88731555
 116567.25251942 235186.44835721 175253.37856596 273684.96578123
 172448.65235754 151484.54136701 205400.11572212 194307.67181584
 108571.24451889 146486.86561196 240222.3663657  206615.77154358
  98192.30364411 283053.50201054 207955.68251956 316807.51468376
 177705.85838673 137290.62818046 147795.00064499 146732.5438466
 150924.77295148 179816.94527257 175251.63785153 228138.82949645
 295854.16025722 241073.18135848 181495.13538737 144756.96415011
 271594.68930372 205125.078